# OutlawBounties — configuration principale
locale: fr        # 'fr' ou 'en'
world: world      # monde ciblé pour les bounties (laisser 'world' par défaut)
teleport:
  ring_min: 36    # distance minimale pour téléporter le joueur autour du monstre
  ring_max: 64    # distance maximale
  countdown_seconds: 3
spawn:
  max_attempts: 80
  avoid_liquids: true
  exclude_worlds: [world_nether, world_the_end]
menu:
  npc_name: "§6Bounty Master"
  title_main: "&8Bounty Hunter"
  title_bounties: "&8Choisir un Bounty"
  title_loot: "&8Récompenses"
  title_shop: "&8Boutique Bounty"
bounties:
  zombie_easy:
    display: "Zombie Facile"
    description: "Échauffement contre un zombie un peu plus costaud."
    entity: ZOMBIE
    health: 40.0
    glowing_seconds: 12
    points_reward: 1
    equipment:
      hand: IRON_SWORD
      head: null
      chest: null
      legs: null
      feet: null
    rewards:
      - item: IRON_INGOT
        min: 3
        max: 7
        chance: 1.0
      - item: GOLD_INGOT
        min: 1
        max: 4
        chance: 0.6
  skeleton_hunter:
    display: "Squelette Chasseur"
    description: "Reste en mouvement!"
    entity: SKELETON
    health: 30.0
    glowing_seconds: 10
    points_reward: 2
    equipment:
      hand: BOW
      head: LEATHER_HELMET
      chest: LEATHER_CHESTPLATE
      legs: LEATHER_LEGGINGS
      feet: LEATHER_BOOTS
    rewards:
      - item: BONE
        min: 4
        max: 10
        chance: 1.0
      - item: ARROW
        min: 16
        max: 32
        chance: 0.9
  enderman_test:
    display: "Enderman Test"
    description: "Ne le regarde pas dans les yeux..."
    entity: ENDERMAN
    health: 40.0
    glowing_seconds: 8
    points_reward: 3
    equipment: {}
    rewards:
      - item: ENDER_PEARL
        min: 2
        max: 5
        chance: 0.8
  witch_curse:
    display: "Sorcière Maudite"
    description: "Attention à ses potions explosives."
    entity: WITCH
    health: 32.0
    glowing_seconds: 10
    points_reward: 2
    equipment: {}
    rewards:
      - item: GLOWSTONE_DUST
        min: 4
        max: 8
        chance: 0.9
      - item: REDSTONE
        min: 6
        max: 12
        chance: 0.7
  pillager_captain:
    display: "Chef Pillard"
    description: "Un capitaine bien armé accompagné de son arbalète."
    entity: PILLAGER
    health: 45.0
    glowing_seconds: 12
    points_reward: 3
    equipment:
      hand: CROSSBOW
      head: IRON_HELMET
      chest: CHAINMAIL_CHESTPLATE
      legs: CHAINMAIL_LEGGINGS
      feet: CHAINMAIL_BOOTS
    rewards:
      - item: EMERALD
        min: 2
        max: 6
        chance: 0.85
      - item: CROSSBOW
        min: 1
        max: 1
        chance: 0.25
  blaze_overlord:
    display: "Blaze Suprême"
    description: "La chaleur augmente à chaque seconde!"
    entity: BLAZE
    health: 36.0
    glowing_seconds: 8
    points_reward: 4
    equipment: {}
    rewards:
      - item: BLAZE_ROD
        min: 2
        max: 5
        chance: 0.9
      - item: MAGMA_CREAM
        min: 1
        max: 3
        chance: 0.6
shop:
  golden_apples:
    display: "Pommes Dorées"
    description: "Un petit coup de pouce pour survivre aux contrats."
    icon: GOLDEN_APPLE
    cost: 4
    item: GOLDEN_APPLE
    amount: 3
  arrow_crate:
    display: "Caisse de Flèches"
    description: "Parfaite pour les chasseurs à distance."
    icon: ARROW
    cost: 2
    item: ARROW
    amount: 48
  totem_bundle:
    display: "Totem de Sauvegarde"
    description: "Une seconde chance quand tout va mal."
    icon: TOTEM_OF_UNDYING
    cost: 15
    item: TOTEM_OF_UNDYING
    amount: 1
